### PR TITLE
A Lua implementation for the benchmark

### PR DESCRIPTION
**Pull request by jzwinck**
This is pretty simple...I tried a variant using the "small performance trick" from the Lua website for reading large files in 8 KB chunks but the difference was not a lot so I decided to stick with this simple implementation.  I'm not a super Lua programmer, so maybe someone can improve on this.

### CODE REVIEW

**Comment by lorca** [comment]
nice, i just tried this but i get an error:

salyari@ubuntu:~/flat_file_benchmark$ lua progs/read_file.lua input/mydata.csv 
lua: progs/read_file.lua:5: attempt to index local `line' (a string value)
stack traceback:
    progs/read_file.lua:5: in main chunk
    [C]: ?
salyari@ubuntu:~/flat_file_benchmark$ lua -v

salyari@ubuntu:~/flat_file_benchmark$ lua progs/read_file.lua input/mydata.csv 
lua: progs/read_file.lua:5: attempt to index local `line' (a string value)
stack traceback:
    progs/read_file.lua:5: in main chunk
    [C]: ?
salyari@ubuntu:~/flat_file_benchmark$ lua -v
Lua 5.0.3  Copyright (C) 1994-2006 Tecgraf, PUC-Rio

**Comment by jzwinck** [comment]
Lua 5.0 is six years old, and should not be used these days.  Current
distros package 5.1 by default, and 5.2 is out now.  Do you think you can
try a newer version?  What version of Ubuntu are you on?

John

On Sun, Feb 19, 2012 at 8:41 PM, lorca <
reply@reply.github.com

**Comment by lorca** [comment]
oh wow.. ubuntu 11.10. i installed via apt-get.  will look into getting the
latest lua.  thanks!

On Sun, Feb 19, 2012 at 7:54 PM, John Zwinck <
reply@reply.github.com

**Comment by jzwinck** [comment]
Try here:
https://launchpad.net/ubuntu/+source/lua5.1/5.1.4-10/+build/2649323

It looks like 5.1 is becoming the default only in 12.04.
On Feb 20, 2012 12:17 AM, "lorca" <
reply@reply.github.com>
wrote:

**Comment by jzwinck** [comment]
Oh, also you can try making a small change which might make it work with
Lua 5.0. Change line:gmatch( to string.gmatch(line, and it may just work.
Probably 5.1 should be used for the actual benchmark though, since it is
closer in vintage to the other tests.
On Feb 20, 2012 12:17 AM, "lorca" <
reply@reply.github.com>
wrote:

**Comment by lorca** [comment]
hey i've added a benchmark for lua 5.1.4.  thanks!

 {"mem": 1901, "program": "lua514", "cpu": "48.2"}

**Pull request merged**
