### PR TITLE
C version of the benchmark

### PR DESCRIPTION
**Pull request by lcapaldo**
I've included compilation in one of the benchmarks since the
other languages have to pay the parse time up front every time.

### CODE REVIEW

**Comment by lorca** [comment]
cool thanks!  i will try this out. and let you know.

why mmap though? and why is it writable?  i imagine mmap would make it
slower or same, but not faster.

-steve

On Sat, Feb 18, 2012 at 4:29 PM, lcapaldo <
reply@reply.github.com

**Comment by lcapaldo** [comment]
It's writable for the same reason I'm using mmap. I turn the \ts and \ns into NULs, in place so I don't have to malloc and copy things so much (I let the OS copy for me (MAP_PRIVATE) a page at a time).

**Comment by lorca** [comment]
oh gotchya, cool thanks.

On Sat, Feb 18, 2012 at 5:43 PM, lcapaldo <
reply@reply.github.com

**Comment by lorca** [comment]
i've added this to the benchmark. http://steve.80cols.com/flat_file_bakeoff.html you win

**Pull request merged**
